name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build .
    - name: test
      run: ctest
    - name: gcov
      run: gcov parse_environ_iovec.test.c
