name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: build
      run:  cmake --build .
    - name: test
      run: ctest
    - name: gcov
      run:  gcov parse_environ_iovec.test.c
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: 9e0119b9-d198-4aa8-b331-2d3ed9ebffa8
